#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# Copyright (c) 2020-Present Mark Spicer

from image_classifier import predictor


if __name__ == '__main__':
    p = predictor.Predictor()
    p.predict()
