#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# Copyright (c) 2020-Present Mark Spicer

from image_classifier import trainer


if __name__ == '__main__':
    t = trainer.Trainer(2)
    t.load()
    t.train()
    t.save()
